server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: EMC2_DBA
    password: EMC2_DBA
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true